trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g vsce
  displayName: 'Instal vsce'

- script: |
    mkdir -p artifacts
    vsce package -o artifacts
  displayName: 'Build Package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: artifacts
    artifactName: Extension Package
