name: CI Checks
on: push
# on:
#   pull_request:
#     branches: [$default-branch]
jobs:
  format_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/set-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: prettier --check '**/*.{js,jsx,ts,tsx}'
